#!/usr/bin/env bash

# post-checkout
# -------------
#
# This hook is invoked when a git checkout is run after having updated the
# worktree. The hook is given three parameters: the ref of the previous HEAD,
# the ref of the new HEAD (which may or may not have changed), and a flag
# indicating whether the checkout was a branch checkout (changing branches,
# flag=1) or a file checkout (retrieving a file from the index, flag=0). This
# hook cannot affect the outcome of git checkout.
#
# It is also run after git clone, unless the --no-checkout (-n) option is used.
# The first parameter given to the hook is the null-ref, the second the ref of
# the new HEAD and the flag is always 1.
#
# This hook can be used to perform repository validity checks, auto-display
# differences from the previous HEAD if different, or set working dir metadata
# properties.

# Log only when env variable isset.
function log() {
    if [[ "yes" == "$IDE_DEBUG" ]]
    then
        echo "[symfony2/hooks/post-checkout] $@"
    fi
}

log "Start hook..."

[ 0 -eq $3 ] && exit 0

log "This is a branch checkout!"

# Warm up the ctags cache
if [[ "true|yes" =~ "$(git config --local --null ide.ctags.warmup)" ]]
then
    /home/nrocco/ide/general/ctags-warmup-cache.sh
fi

# Warm up the ctrlp cache
if [[ "true|yes" =~ "$(git config --local --null ide.ctrlp.warmup)" ]]
then
    /home/nrocco/ide/general/ctrlp-warmup-cache.sh
fi

# Warn if there are database changes
/home/nrocco/ide/symfony2/detect-database-changes.sh $1 $2

# Warn if there are composer changes
/home/nrocco/ide/symfony2/detect-composer-changes.sh $1 $2

# Warn if there are parameters changes
/home/nrocco/ide/symfony2/detect-parameters-changes.sh $1 $2

log "Done."
