before:
  hooks:
    - go mod download
    - apk add protobuf
    - go get -u github.com/golang/protobuf/protoc-gen-go
    - protoc -I server/ server/server.proto --go_out=plugins=grpc:server
builds:
- env:
  - "CGO_ENABLED=0"
  flags:
  - "-v"
  - "-tags=netgo"
  ldflags:
  - "-d -s -w -X cmd.version={{.Version}} -X cmd.commit={{.ShortCommit}} -X cmd.buildDate={{.Date}}"
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
