---
services:
  go:
    build:
      context: .
      target: godev
    init: true
    command: ["sleep", "infinity"]
    working_dir: "${PWD}"
    volumes:
      - "${PWD}:${PWD}"
      - "go_cache:/root/.cache"
      - "go_pkg:/go/pkg"
volumes:
  go_cache:
  go_pkg:
