#!/bin/bash -e

# Include common functions
. "$IDE_PATH/lib/functions.sh" || exit 1


#############################################################################
#############################################################################


LANGUAGE=$(__ide_config ide.project.language)
CTAGS_CONFIG="$IDE_PATH/configs/$LANGUAGE/ctags"


log "Warming up the ctags cache..."
log "Using ctags options file $CTAGS_CONFIG"


if [[ '--vendors' == "$1" ]]
then

    log "Creating tags in ${GIT_DIR}/tags_vendors"

    case "$LANGUAGE" in

        php/*)
            log "Php style project detected"
            find vendor -type f -name '*.php' | ctags -L - --tag-relative --options=${CTAGS_CONFIG} -o ${GIT_DIR}/tags_vendors > /dev/null 2>&1
            ;;

        python/*)
            log "Python style project detected"
            find env/lib/*/site-packages -type f -name '*.py' | ctags -L - --tag-relative --options=${CTAGS_CONFIG} -o ${GIT_DIR}/tags_vendors > /dev/null 2>&1
            ;;

        *)
            logerr "Oops, don't know what kind of project this is..."
            exit 1
            ;;

    esac

else

    log "Creating tags in ${GIT_DIR}/tags"
    git ls-files | ctags -L - --tag-relative --options=${CTAGS_CONFIG} -o ${GIT_DIR}/tags > /dev/null 2>&1

fi

log "Done."
