#!/usr/bin/env bash

LANGUAGE=$(__ide_config ide.project.language)
CTAGS_OPTS=$(__get_default_ctags_options "$LANGUAGE")


log "Warming up the ctags cache..."
log "Using ctags options: $CTAGS_OPTS"


if [[ '--vendors' == "$1" || '--vendor' == "$1" ]]
then

    log "Creating tags in ${IDE_GIT_DIR}/tags_vendors"

    case "$LANGUAGE" in

        php/*)
            log "Php style project detected"
            find vendor -type f -name '*.php' | ctags -L - --tag-relative=yes ${CTAGS_OPTS} -o ${IDE_GIT_DIR}/tags_vendors > /dev/null
            ;;

        python/*)
            log "Python style project detected"
            find env/lib/*/site-packages -type f -name '*.py' | ctags -L - --tag-relative=yes ${CTAGS_OPTS} -o ${IDE_GIT_DIR}/tags_vendors > /dev/null
            ;;

        *)
            logerr "Oops, don't know what kind of project this is..."
            exit 1
            ;;

    esac

else

    log "Creating tags in ${IDE_GIT_DIR}/tags"
    git ls-files | ctags -L - --tag-relative=yes ${CTAGS_OPTS} -o ${IDE_GIT_DIR}/tags > /dev/null

fi

log "Done."
