#!/bin/bash -e

# Include common functions
. "$IDE_PATH/lib/functions.sh" || exit 1


#############################################################################
#############################################################################


# Determine location of the cache file
PROJECT="$(git rev-parse --show-toplevel)"
CACHE_DIR="$HOME/.cache/ctrlp"
CACHE_FILE="${CACHE_DIR}/${PROJECT//\//%}.txt"


# Find out what needs to be ignored
LOCAL_IGNORE=$(__ide_config_local ide.ctrlp.ignore '')
GLOBAL_IGNORE=$(__ide_config_global ide.ctrlp.ignore '')
PRUNE_DIRS=( ${GLOBAL_IGNORE[@]} ${LOCAL_IGNORE[@]} )


# Show some helpful output
log "Warming up the ctrlp cache..."
log " - global: ide.ctrlp.ignore = ${GLOBAL_IGNORE[@]}"
log " - local:  ide.ctrlp.ignore = ${LOCAL_IGNORE[@]}"
log " - cache:  $CACHE_FILE"


# Start caching all the things
for dir in "${PRUNE_DIRS[@]}"
do
    prune="$prune -path '*/$dir' -prune -or"
done

find * $prune \( -type f -print \) | \grep -v __pycache__ > "$CACHE_FILE"


log "Done."
