#!/usr/bin/env bash

# Determine location of the cache file
PROJECT="$(git rev-parse --show-toplevel)"
CACHE_DIR="$HOME/.cache/ctrlp"
CACHE_FILE="${CACHE_DIR}/${PROJECT//\//%}.txt"


# Find out what needs to be ignored
LOCAL_IGNORE=$(__ide_config_local ide.ctrlp.ignore || true)
GLOBAL_IGNORE=$(__ide_config_global ide.ctrlp.ignore || true)
PRUNE_DIRS=( ${GLOBAL_IGNORE[@]} ${LOCAL_IGNORE[@]} )


# Show some helpful output
log "Warming up the ctrlp cache..."
log " - global: ide.ctrlp.ignore = ${GLOBAL_IGNORE[@]}"
log " - local:  ide.ctrlp.ignore = ${LOCAL_IGNORE[@]}"
log " - cache:  $CACHE_FILE"


# Start caching all the things
for dir in "${PRUNE_DIRS[@]}"
do
    prune="$prune -name $dir -o"
done

prune=$(echo $prune | sed "s/ -o$//g")

find * -type d '(' $prune ')' -prune -o -type f > "$CACHE_FILE"

log "Done."
