#!/bin/bash -e

# Include common functions
. "$IDE_PATH/lib/functions.sh" || exit 1


#############################################################################
#############################################################################


cat << EOF 1>&2
usage: git ide [$(__ide_get_subcommands)]

ide provides a powerful ide that gets out of your way.

available sub commands:

    help            print this help and exit
    ctags           (re)generates the tags file
    ctrlp           (re)generates the ctrlp cache file
    symfony         provides checks for symfony2 based projects
EOF
