#!/usr/bin/env bash

LANGUAGE="$(__ide_config_local ide.project.language)"

SUBCOMMAND="$1"
shift

if [ -z "${SUBCOMMAND}" ]
then
    echo "usage: git ide hooks list"
    echo "       git ide hooks show [hook]"
    echo "       git ide hooks [enable|disable] hook"
    echo "       git ide hooks exec [hook]"
    exit

elif [[ "list" == "${SUBCOMMAND}" ]]
then
    log_section "Available hooks for ${LANGUAGE}"
    ls "$IDE_PATH/hooks/$LANGUAGE"
    exit

elif [[ "show" == "${SUBCOMMAND}" ]]
then
    log_section "Show hook ${1} for ${LANGUAGE}"
    cat "$IDE_PATH/hooks/$LANGUAGE/$1"
    exit

elif [[ "enable" == "${SUBCOMMAND}" ]]
then
    echo -e "#!/usr/bin/env bash\nexec git ide hooks exec $1" '"$@"' > ".git/hooks/$1" && \
    chmod +x ".git/hooks/$1"
    log "Enabled git ide hook .git/hooks/$1"
    exit

elif [[ "disable" == "${SUBCOMMAND}" ]]
then
    rm ".git/hooks/$1"
    log "Disabled git ide hook .git/hooks/$1"
    exit

elif [[ "exec" == "${SUBCOMMAND}" ]]
then
    HOOK="$1"
    shift

    if [ ! -x "$IDE_PATH/hooks/$LANGUAGE/$HOOK" ]
    then
        logerr "Unsupported hook: $HOOK"
        exit 1
    fi

    exec "$IDE_PATH/hooks/$LANGUAGE/$HOOK" "$@"

fi
