#!/bin/bash -e

# Include common functions
. "$IDE_PATH/lib/functions.sh" || exit 1


#############################################################################
#############################################################################


if LANGUAGE=$(__ide_config ide.project.language)
then
    logerr "The repository is already setup as a $LANGUAGE project."
    exit 1
fi

log "Setting up the repository as a ide project..."
echo "TODO"
