#!/usr/bin/env bash

if LANGUAGE=$(__ide_config ide.project.language)
then
    logerr "The repository is already setup as a $LANGUAGE project."
    exit 1
fi

log "Setting up the repository as a ide project..."

auto_lang=$(__ide_detect_project_language)

log "What type of project are you running here?"
echo -n "[$auto_lang] "

read chosen_lang

if [ -z "$chosen_lang" ]
then
    lang=$auto_lang
else
    lang=$chosen_lang
fi

log "Setting the project language to: $lang"
git config --local ide.project.language "$lang"
