#!/usr/bin/env bash

if ! LANGUAGE=$(__ide_config ide.project.language)
then
    logerr "The repository is not initialized yet. Use 'git ide init' to initialize."
    exit 1
fi

log_section "local options"
git config --local --get-regexp '^ide' | while read key value; do
    echo "$key = $value"
done

echo

log_section "global options"
git config --global --get-regexp '^ide' | while read key value; do
    echo "$key = $value"
done

echo

log_section "enabled hooks"
find .git/hooks -perm +0111 -a -not -type d -a -not -name '*.sample'
