#!/bin/bash -e
IDE_PREFIX="ide/symfony2"

test -z "$IDE_PATH" && exit 1

# Include common functions
. "$IDE_PATH/lib/functions.sh"


function __detect_composer_changes() {
    if ! git --no-pager diff --exit-code --quiet --name-only $1 $2 -- composer.json composer.lock
    then
        logerr "changes in composer detected! you might want to run composer install"
    fi
}


function __detect_database_changes() {
    if ! git --no-pager diff --exit-code --quiet --name-only $1 $2 -- app/DoctrineMigrations
    then
        log "changes in migrations detected! you might want to run php app/console doctrine:migrations:migrate"
    fi
}


function __detect_parameters_changes() {
    if ! git --no-pager diff --exit-code --quiet --name-only $1 $2 -- app/config/parameters.yml.dist
    then
        log "changes in parameters.yml detected! you might want to check it out."
    fi
}


if [ -z "$1" ]
then
    logerr "Usage: git ide symfony2 [composer-changes|database-changes|parameters-changes|check_all] from to"
    exit 1
fi


SUBCOMMAND="$1"
shift
log "subcommand $SUBCOMMAND"


if [[ -z $1 || -z $2 ]]
then
    logerr "Usage: git ide symfony2 $SUBCOMMAND from to"
    exit 1
fi


case "$SUBCOMMAND" in
    composer-changes)
        __detect_composer_changes "$@"
        ;;
    database-changes)
        __detect_database_changes "$@"
        ;;
    parameters-changes)
        __detect_parameters_changes "$@"
        ;;
    check_all)
        __detect_composer_changes "$@"
        __detect_database_changes "$@"
        __detect_parameters_changes "$@"
        ;;
esac
