#!/usr/bin/env bash

BRANCH_NAME=$(git symbolic-ref -q HEAD)
BRANCH_NAME=${BRANCH_NAME##refs/heads/}
ISSUE_KEY=$(echo $BRANCH_NAME | grep -oE '[a-zA-Z]+-[0-9]+' | tr '[:lower:]' '[:upper:]')

if [ -n "$ISSUE_KEY" ]
then
    sed -i.bak -e "1s/^/$ISSUE_KEY /" $1
fi
