#!/usr/bin/env bash

# Only continue if this is a branch checkout
[[ 0 -eq $3 ]] && exit 0

# Warm up the ctags cache
git ide ctags

# Warm up the ctrlp cache
git ide ctrlp

# Alert the user if there are changes in parameters.yml.dist
if ! git --no-pager diff --exit-code --quiet --name-only "$1" "$2" -- app/config/parameters.yml.dist
then
    log "Changes in parameters.yml detected!"
    log "    vimdiff app/config/parameters.yml app/config/parameters.yml.dist"
fi

# Alert the user if there are changes to composer
if ! git --no-pager diff --exit-code --quiet --name-only $1 $2 -- composer.json composer.lock
then
    log "Changes in composer detected!"
    log "    composer install"
fi

# Alert the user if there are changes to Doctrine Migrations
if ! git --no-pager diff --exit-code --quiet --name-only $1 $2 -- app/DoctrineMigrations
then
    log "Changes in migrations detected!"
    log "    php app/console doctrine:migrations:migrate"
fi
