---
name: tags
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Install tools
        run: go get -u golang.org/x/lint/golint
      - name: Lint and Test
        run: make lint vet test
      - name: Create Release
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
